Validate Deployment
Signed-off-by: prxt <prxt@6529.io>

Signed-off-by: Analytics Flow <info@analyticsflow.ee>

diff --git a/.github/workflows/build-upload-s3.yml b/.github/workflows/build-upload-s3.yml
--- a/.github/workflows/build-upload-s3.yml
+++ b/.github/workflows/build-upload-s3.yml
@@ -62,6 +62,15 @@ jobs:
           --version-label "${{ env.COMMIT_SHA }}" \
           --description "${DESCRIPTION:0:100}"
 
+      - name: Validate Deployment
+        run: |
+          INSTANCE_COUNT=$(aws elasticbeanstalk describe-environment-resources --environment-name Seizeapp-env --region us-east-1 --query "EnvironmentResources.Instances[*].Id" --output text | wc -w)
+          echo "Instance count: $INSTANCE_COUNT"
+          if [[ "$INSTANCE_COUNT" -lt 2 ]]; then
+            echo "Deployment Aborted: Less than 2 instances are running."
+            exit 1
+          fi
+
       - name: Deploy new Version to ElasticBeanstalk
         run: |
           aws elasticbeanstalk update-environment \
